apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: exceptionless-api-weebhook
  labels:
    app: exceptionless-api-weebhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exceptionless-api-weebhook
  template:
    metadata:
      labels:
        app: exceptionless-api-weebhook
    spec:
      containers:
        - name: exceptionless-api-weebhook
          image: "justmine/exceptionless.api.webhook:0.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  namespace: geekbuying-light-addons
  name: exceptionless-api-weebhook
  labels:
    app: exceptionless-api-weebhook
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: exceptionless-api-weebhook
